### ISSUE TITLE
Admins unable to click on past slots

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/volunteers#122]
Currently, past events don't let anybody click on the slots. Admins and department leads should still be able to click on them so they can report who flaked / who did a good job.

**Comment by Meleeman01** [comment]
good point, so only admin and depart leads should be able to click on past slots.

**Comment by Meleeman01** [comment]
yeah I looked into this, the problem is a bit deeper than that, whenever an Event is updated, it loses their schedule and slots, it's still in the database, but for some reason it won't show any of the slots after an even has been updated.
