### ISSUE TITLE
Don't remove slots that users have signed up for

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/volunteers#123]
Currently when you change the times or dates of a volunteer shift, all the slots are deleted. Instead, only empty slots should be deleted and it shouldn't be possible to remove a slot that somebody has signed up for.

This would force the admin to either contact the user, remove them from the shift manually, or move them to another slot.

**Comment by Meleeman01** [comment]
https://github.com/playasoft/volunteers/pull/125 got it! :DDDDDD
