### ISSUE TITLE
Additional details on nginx config?

### ISSUE THREAD

**Issue by se7enmilgram** [playasoft/volunteers#128]
Greetings from your southern neighbors in New Mexico!

We're trying to up our volunteer organization game, and I've taken a stab at getting VolDB up and running an an ubuntu 18.0.4 system using the steps you specified. Got through most of the initial tasks and added dependencies, but I think I'm missing parts of my nginx configuration. If this were running on apache, I'd say I was missing mod_rewrite. The index loads, but when I'm directed to /login or /register, I get a 404. 

Any guidance would be a big help. This looks like a great volunteer management platform and I'm very excited to try to get it off the ground.

**Comment by itsrachelfish** [comment]
Hey there! I'd love to hear more about your event.

This is the nginx configuration we're currently using for Apogaea - https://gist.github.com/itsrachelfish/6a597bbd2071629193ec3eb891ffcf69

We use LetsEncrypt for free SSL, and if you're curious about all those `ssl_ciphers`, they're recommendations from this Mozilla security guide - https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by se7enmilgram** [comment]
LE is the business. I'll take a look at this and see if I can suss out what
I've done wrong.

Our event is called Sunburn, and takes place at an old west movie set
outside of Santa Fe. We actually get to fill a town with bars and banks and
a jail.

**Comment by itsrachelfish** [comment]
That sounds really cool! How many people go to Sunburn? Santa Fe isn't too far away, maybe I'll have to come check it out :slightly_smiling_face:

**Comment by se7enmilgram** [comment]
This year's population cap will be at least 250. We'd love to see more of our northern neighbors get involved! Best way to contact me privately is https://keybase.io/crim

**Comment by se7enmilgram** [comment]
Found my issues, thanks for assistance.
