### ISSUE TITLE
JS validation clobbering custom start_time and duration in Shift edit.

### ISSUE THREAD

**Issue by se7enmilgram** [playasoft/volunteers#132]
The problem occurs with custom values with single digit results of the hours field (because 2:00 isn't in the form HH:mm). When the form loads these error out and revert back to unfilled form fields, requiring them to be re-entered before submitting a change. Resolved by zero padding the hours in the formatTimes function of the Schedule model. I'm less certain what implications this may have elsewhere...

Looks like the new commit was added to the existing PR #131. I would have liked to submit a separate PR but am a bit of a git noob.

**Comment by itsrachelfish** [comment]
@se7enmilgram after reviewing all of our old issues, it looks like this is a duplicate of #68, except you actually determined what the problem was :+1:

**Comment by Meleeman01** [comment]
got it. The JS was only a symptom of the problem. https://github.com/playasoft/volunteers/pull/149

**Comment by se7enmilgram** [comment]
oh word, my understanding of how the JS validation and PHP validation are linked within the software is tenuous at best.
