### ISSUE TITLE
Username when removing a volunteer could be blank

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/volunteers#134]
https://github.com/playasoft/volunteers/blob/master/laravel/app/Http/Controllers/SlotController.php#L175

The `burner_name` column isn't a required field so it's possible the username would be blank. This notification should use the same logic as the slot template to display either the burner name or their username as a fallback.

**Comment by Meleeman01** [comment]
i addressed this in another pull request, https://github.com/playasoft/volunteers/pull/126
