### ISSUE TITLE
Error when signing up for a shift as an admin

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/volunteers#141]
You see the following error message when you try to click the "Take shift" button on the slot page while logged in as an admin (For example `http://voldb.local/slot/1409/view`)

![Screenshot from 2019-03-13 20-02-48](https://user-images.githubusercontent.com/1670549/54326144-17b61f80-45cb-11e9-8b0c-2320dcf65342.png)

Originally reported by an Apogaea admin, I was able to replicate this on my local instance as well.

**Comment by se7enmilgram** [comment]
Same thing is now happening on the SunBurn instance - have we got a root cause yet or should I take a look?
