### ISSUE TITLE
User search only works in Firefox

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/volunteers#145]
There is a javascript error which is preventing this feature from working in Chrome and Safari.

![user-search-error](https://user-images.githubusercontent.com/1670549/55114702-45f62d80-50a8-11e9-831e-c0bae0387b71.png)

**Comment by Meleeman01** [comment]
weird that it only works in firefox. but yeah i think there's just a class that needs to be removed. check this out. https://github.com/playasoft/volunteers/pull/146
