### ISSUE TITLE
Printable department report erroring on display name helper

### ISSUE THREAD

**Issue by se7enmilgram** [playasoft/volunteers#162]
We're starting to stage for sunburn and aren't able to print out the dept reports because of this issue. It's really stressing the volunteer leads out. CSV export works fine. I'm guessing it's related to the displayname helper changes. 

![C6E85715-1FC3-4E39-A1D2-4D399CC9DA25](https://user-images.githubusercontent.com/2394457/59964700-40e72580-94c1-11e9-914c-14fc56620b15.png)

**Comment by itsrachelfish** [comment]
@se7enmilgram As a quick fix, you can use a previous version of the repo before the displayname function was added -

```
git checkout 67b4579215ae68aceb7b8c5e282320b72b60263f
```

Also @demogorgonzola is working on a fix now :+1:
