### ISSUE TITLE
Basic API endpoints for volunteer check in

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/volunteers#178]
The volunteer check in project is a planned mobile app which integrates with the volunteer database. https://github.com/playasoft/voldb-check-in/wiki/Requirements

The app is already set up to connect to the volunteer database using standard laravel cookie based auth, so we only need the following endpoints with standard user authentication:

## `GET /v1/profile`
Returns information about the current user account (if logged in). Otherwise returns a 401 error.

```json
{
    "username": "rachel",
    "email": "rachel@wetfish.net",
    "permissions": ["volunteer", "admin", "ranger"],
    "full_name": "Rachel Fish",
    "burner_name": "BlubBlub",
    "phone_number": "555-123-4567"
}
```

## `GET /v1/events`
Returns an array of all events with basic information like the name, start, and end dates.

```json
[
    {
        "id": "1",
        "name": "Apogaea 2017",
        "start_date": "2017-06-07",
        "end_date": "2017-06-12"
    },

    {
        "id": "2",
        "name": "Denver Decompression 2018",
        "start_date": "2018-10-12",
        "end_date": "2018-10-14"
    },

    {
        "id": "3",
        "name": "Apogaea 2019",
        "start_date": "2019-06-05",
        "end_date": "2019-06-10"
    }
]
```

## `GET /v1/event/[id]/departments`
Returns an array of all departments within the specified event ID.

```json
[
    {
        "id": "1",
        "name": "Acculturation"
    },

    {
        "id": "2",
        "name": "BAMF"
    },

    {
        "id": "3",
        "name": "Cat Herder"
    }
]
```

## `GET /v1/event/[id]/roles`
Returns an array of all roles within the specified event ID. Each role belongs to a specific department. (Development note: Because issue #114 has not been addressed yet, we are calling these roles in the API but in the database they are called shifts.)

```json
[
    {
        "id": "1",
        "department_id": "19",
        "name": "New Ranger"
    },

    {
        "id": "2",
        "department_id": "19",
        "name": "Returning Dirt Ranger"
    },

    {
        "id": "3",
        "department_id": "19",
        "name": "Ranger Khaki"
    }
]
```

## `GET /v1/event/[id]/shifts`
Returns an array of all shifts within the specified event ID. Each shift belongs to a role and also belongs to a department. (Development note: Because issue #114 has not been addressed yet, we are calling these shifts in the API but in the database they are called slots.)

```json
[
    {
        "id": "1",
        "department_id": "5",
        "role_id": "10",
        "start_date": "2017-06-09",
        "end_date": "2017-06-09",
        "start_time": "18:00:00",
        "end_time": "22:00:00",
        "user_id": "1",
        "email": "cool@volunteer.net",
        "full_name": "Volunteer McVolunteererson",
        "display_name": "Cool Volunteer",
        "status": null,
    },

    {
        "id": "2",
        "department_id": "5",
        "role_id": "10",
        "start_date": "2017-06-09",
        "end_date": "2017-06-09",
        "start_time": "18:00:00",
        "end_time": "22:00:00",
        "user_id": "2",
        "email": "friendo@myspace.com",
        "full_name": "Buddy Friendo",
        "display_name": "Friendo",
        "status": "flaked"
    },

    {
        "id": "3",
        "department_id": "5",
        "role_id": "10",
        "start_date": "2017-06-09",
        "end_date": "2017-06-09",
        "start_time": "18:00:00",
        "end_time": "22:00:00",
        "user_id": "3",
        "email": "jellyfish@theocean.org",
        "full_name": "Pelagia noctiluca",
        "display_name": "Jellyfish",
        "status": "ontime"
    }
]
```

## `POST /v1/shift/[id]`
Submits the user's performance to the server for the specified shift.

```json
{
    "status": "ontime"
}
```

**Comment by demogorgonzola** [comment]
So first pass at this, this seems straight-forward. We just copy whatever middleware each controller has to the api controllers and write some simple queries to pull in the concerning data which we pack to JSON.

I'll start with a first draft!
