### ISSUE TITLE
Admin updating user profiles

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/volunteers#18]
The current Apogaea Volunteer Database allows admins to edit the profiles of other users. Currently in laravel-voldb admins can only view other profiles and change user roles.

**Comment by kelsh** [comment]
Change username and email as well?  I could imagine some chaos from being able to change username.  email maybe is fine.

**Comment by itsrachelfish** [comment]
@kelsh Anything a user has access to change in their profile, admins should be able to edit. Username, email, playa name, emergency contact, etc.
