### ISSUE TITLE
Updating Existing Build

### ISSUE THREAD

**Issue by Peabo83** [playasoft/volunteers#190]
Hello! I want to start by saying that this is a great repo. We are looking at it for our event and we setup a test of it last year. I see that since then there have been some updates and I was wondering if updating is as easy as I think it is. If I just dump the most recent files in, will it be good to go, or were there any database updates?

Thank you for this!

**Comment by itsrachelfish** [comment]
@Peabo83 We recommend using git to track changes and make updates to your installation. If you used `git clone` to set up the project on your server you can simply run `git pull` to fetch the latest code.

There have been a few changes to the database in the past year, so you will need to run the latest migrations. Regardless of if you used git or copy the files onto your server manually, all database migrations are automatically handled by Laravel. Simply run `php artisan migrate` on the command line and your database will be updated.

By the way, if you ever need help I would encourage you to send me an email (rachel@wetfish.net) or you can join our chatroom! (https://chat.wetfish.net)
