### ISSUE TITLE
Volunteer accountability

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/volunteers#25]
At the event, it will be important for administrators and shift leads to be able to mark who attended their volunteer shifts. This information could be used as a reward system (offering swag to good participants) and to identify potential red flags (users who flaked on multiple shifts).

Could be rolled into the shift report feature (issue #22)

**Comment by IzKen** [comment]
For the past three years Cat Hearders and shift leads were supposed to report back no shows to Info or Vol Booth. This info was then written down, or put into an XLSX in 2014, not sure what they did in 2016. 

So good feature request, but low priority. We may not have good enough data service to update this info until after the event anyways.

**Comment by itsrachelfish** [comment]
I was thinking it'd be cool if the printable reports had circles you could fill in (like a ballot) to say if someone flaked or how well they did. Then we could use a computer to scan all of the results.

Low priority haha.

**Comment by itsrachelfish** [comment]
Duplicate of #73, solved as of #116 

:heart:
