### ISSUE TITLE
Create new user group for 'event admins'

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/volunteers#30]
There should be a new user group for 'event admins' that has less permissions than the normal admin user group. Event admins should have access to all admin features except the following:

- Create events
- Receiving user registration / upload notifications

**Comment by IzKen** [comment]
My comment on #28, I think this can be moved to a post event milestone

**Comment by itsrachelfish** [comment]
The original idea behind this feature was to have a single database with lots of different events in it, each with their own sets of admins, for example different admins for each regional. This creates a single point of failure and unnecessary complexity. 

In practice events prefer having their own instance of the database they can customize specific to their event.
