### ISSUE TITLE
Edit scheduled shift Start Time set to "Select Time" instead of the actual start time.

### ISSUE THREAD

**Issue by chrisdobell** [playasoft/volunteers#68]
Steps to reproduce:
 1. Go to https://volunteer.apogaea.com/schedule/42/edit
 2. The Start Time field is not the start time but is just blank "Select Time" (see attached)
![edit_scheduled_shift_start_time_set_to_nothing](https://cloud.githubusercontent.com/assets/25570108/25064320/3308c3a0-21b5-11e7-8cb3-631a42960672.png)

**Comment by itsrachelfish** [comment]
@chrisdobell Is this issue still happening for you? I can't reproduce it. What browser are you using? I'm assuming chrome?

**Comment by chrisdobell** [comment]
@itsrachelfish Yes.  I'm using Chrome.  I'm on a Mac. Try the Wed Gate Regular (first line regular).  I think it has something to do with recurring, multi-day scheduled shifts.

**Comment by itsrachelfish** [comment]
I think it's because this shift uses a custom start time / custom duration. Start time should automatically become "Other" on page load. I'm using Firefox and "Other" is automatically selected. Going to need to test in Chrome.

**Comment by itsrachelfish** [comment]
It looks like this is still a problem - #132
