### ISSUE TITLE
Admin shift assignment revocation

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/volunteers#71]
It should be possible for admins and department leads to remove users from slots. This should only apply to upcoming events, it should not be possible to change an event after it has occured.

Pretty simple update, just requires a "remove" button in the slot template and a new route to remove the `user_id` from the `Slot`. 

Related to: #121

**Comment by Meleeman01** [comment]
I got it done https://github.com/playasoft/volunteers/pull/124

**Comment by itsrachelfish** [comment]
@Meleeman01 Thanks for following up! Feel free to close issues after you've finished them :slightly_smiling_face:
