### ISSUE TITLE
Add shift review page for department leads to mark shifts as flaked or not

### ISSUE THREAD

**Issue by chrisdobell** [playasoft/volunteers#74]
This page, for both web and mobile, would provide a list of all shifts within the department-lead user's department.  It could have a drop down menu to select day vs. a long list of all the days.  The listing of shifts would have columns shift, user, starttime, endtime/duration, review with the review column being either a flake checkbox (boolean) or a drop down of choices like "flake, late, satisfactory, awesome".  This would allow a mobile app to download a department-leads's shifts before the event but allow offline storage of reviews to be uploaded when there is interweb access.

**Comment by Meleeman01** [comment]
so does this page have to be able to download to the client device right? i got an idea of what that looks like. so it be |: shift | user | starttime | endtime | duration | flake dropdown here...|}
and list each row of volunteers that volunteered for a shift.

**Comment by chrisdobell** [comment]
Yes, regular CRUD web page to change the flake column (assuming this part of the work has already been done) in the database.

**Comment by itsrachelfish** [comment]
@chrisdobell Yep, the flake column was finally added to the database. :slightly_smiling_face: 

Currently it can only be edited by clicking on a slot, changing the value of a dropdown, and then saving. Quite a tedious process if you need to input a lot of data at once.

I agree there should be a custom page which lists all of the shifts that people signed up for in each department, similar to the information displayed in the printable department report.

**Comment by Meleeman01** [comment]
got it https://github.com/playasoft/volunteers/pull/157

**Comment by Meleeman01** [comment]
![image](https://user-images.githubusercontent.com/13123926/59308984-0d59ff00-8c68-11e9-9288-c77582cda4db.png)

as of now this is what it looks like

**Comment by itsrachelfish** [comment]
This has been completed for some time now and is actively being used by Apogaea :tada:
