### ISSUE TITLE
TimeLine mismatch

### ISSUE THREAD

**Issue by mybirthdays** [playasoft/volunteers#98]
When you are adding a shift to the schedule if you select the start time as noon it will add it to the timeline starting at 5pm and say in the timeline blob 12:00pm.  See attached
![screen shot 2018-01-23 at 8 56 52 am](https://user-images.githubusercontent.com/35737329/35286221-a07aacbe-001c-11e8-9df4-fd8e263a0856.png)

**Comment by itsrachelfish** [comment]
I'm impressed "noon" even does anything. It's supposed to be a time format (1:00 pm, 13:00, etc.).

@devnill What do you think about updating the front end to allow for typing "noon" / "midnight"? Or should we display an error message?

@mybirthdays Thanks for the bug report!

**Comment by mybirthdays** [comment]
Noon is a dropdown option, as is midnight.  I made it work by selecting a time and setting it to 12:00pm and everything works fine.  Not as much of an issue for me I have all the shifts entered. Just something I thought would be good before APO gets it's hands on it...

**Comment by Meleeman01** [comment]
i tried to replicate the error and it seems to be working normally.  i couldn't replicate it.
